- README.MD
Nog wat klein spul voor de README.MD
> Small fixes to the readme file

- saltgui/index.html
- saltgui/static/scripts/api.js
- saltgui/static/scripts/routes/home.js
- saltgui/static/stylesheets/home.css
poging 2, rebased en zonder code in comments
> Inactivejobs

- saltgui/static/scripts/api.js
- saltgui/static/scripts/routes/login.js
- saltgui/static/stylesheets/home.css
- saltgui/static/stylesheets/main.css
Solution for session timeout. Does not cover all session timout effects, but at least the page-refresh of the home screen returns to the login screen.
Also made the username/password fields readonly on succesful login. The still blinking cursor is then prevented.
> Sessiontimeout

- saltgui/index.html
> promoted ldap because it was tested ok

- package.json
- runtests.sh
- saltgui/index.html
- saltgui/static/scripts/api.js
- saltgui/static/scripts/router.js
- saltgui/static/scripts/routes/job.js
- saltgui/static/scripts/routes/keys.js
- saltgui/static/scripts/routes/login.js
- saltgui/static/scripts/routes/minions.js
- saltgui/static/scripts/utils.js
- saltgui/static/stylesheets/dropdown.css
- saltgui/static/stylesheets/login.css
- saltgui/static/stylesheets/main.css
- saltgui/static/stylesheets/page.css
- tests/functional/login.js
- tests/helpers/wait-for-docker.js
- tests/unit/parsecmdline.js
- tests/unit/utils.js
- yarn.lock
I introduced some css linting, see https://github.com/stylelint/stylelint-config-standard
Also I replaced jshint with eslint which is the defactor standard right now and easy to adjust the rules. I added some rules based on what makes sense + the feedback of @oliverdunk, see package.json in this pull request for details.
@erwindon Do you agree with these linting rules? Feel free to adjust in this pull request. When agreed, could you merge?
> Eslint and stylelint

- package.json
- saltgui/static/scripts/api.js
- saltgui/static/scripts/documentation.js
- saltgui/static/scripts/dropdown.js
- saltgui/static/scripts/output.js
- saltgui/static/scripts/parsecmdline.js
- saltgui/static/scripts/router.js
- saltgui/static/scripts/routes/job.js
- saltgui/static/scripts/routes/keys.js
- saltgui/static/scripts/routes/login.js
- saltgui/static/scripts/routes/minions.js
- saltgui/static/scripts/routes/page.js
- saltgui/static/scripts/routes/route.js
- saltgui/static/scripts/utils.js
- tests/functional/login.js
- tests/unit/output.js
- tests/unit/utils.js
I'm confusing myself often with the different use of `let` and `var`. Most of the new code that was contributed lately uses `let`. This PR changes all code to `let` and validates that code that no `var` still appear.
For viewers that want more details: see https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var-to-declare-a-variable-in-jav
> replace VAR with LET/CONST

- saltgui/static/scripts/api.js
- saltgui/static/scripts/dropdown.js
- saltgui/static/scripts/parsecmdline.js
- saltgui/static/scripts/routes/keys.js
- saltgui/static/scripts/routes/page.js
- tests/functional/login.js
JS has an identity(`===`) and an equality(`==`) operator. In most situations, the identity operator is the right one. This PR updates all of the `==` to `===`; and also `!=` to `!==`.
> use identity operator instead of equality

- saltgui/static/scripts/commandbox.js
- saltgui/static/scripts/output.js
- saltgui/static/scripts/routes/job.js
- saltgui/static/stylesheets/job.css
- saltgui/static/stylesheets/page.css
This PR makes the output in the command-box collapsible.
This is determined per output format.
Single-line output is exempt.
See also #25 
A new status line tells how many minions returned data.
This line also has the control to (un)collapse all.
> make output collapsable

- saltgui/index.html
- saltgui/static/scripts/commandbox.js
- saltgui/static/scripts/documentation.js
- saltgui/static/scripts/dropdown.js
- saltgui/static/scripts/output.js
- saltgui/static/scripts/runtype.js
- saltgui/static/stylesheets/page.css
> run jobs aynchronously 

- saltgui/index.html
- saltgui/static/scripts/api.js
- saltgui/static/scripts/output.js
- saltgui/static/scripts/router.js
- saltgui/static/scripts/routes/grains.js
- saltgui/static/scripts/routes/grainsminion.js
- saltgui/static/scripts/routes/job.js
- saltgui/static/scripts/routes/keys.js
- saltgui/static/scripts/routes/login.js
- saltgui/static/scripts/routes/minions.js
- saltgui/static/scripts/routes/page.js
- saltgui/static/scripts/routes/pillars.js
- saltgui/static/scripts/routes/pillarsminion.js
- saltgui/static/stylesheets/grains.css
- saltgui/static/stylesheets/page.css
- saltgui/static/stylesheets/pillars.css
A new page which shows an overview of the number of pillars per minion.
Then zoom in on the minion and see all pillars.
Initially the details are hidden. Information can be revealed by clicking on it.
> Added a page with pillar information

- saltgui/static/scripts/routes/page.js
sometimes multiple IP numbers are shown
> fix issues with multiple ipv4 numbers

- docker/conf/master
This could help during testing and can be useful for new users to explore all SaltGUI features
> Add simple templates configuration

- docker/srv/salt/top.sls
- saltgui/static/scripts/routes/keys.js
- saltgui/static/sorttable/sorttable.js
- saltgui/static/stylesheets/dropdown.css
- saltgui/static/stylesheets/login.css
- saltgui/static/stylesheets/main.css
- saltgui/static/stylesheets/page.css
> minimal ux improvment for: table, font, color, msg

- saltgui/index.html
- saltgui/static/stylesheets/page.css
> Add link to project on github on login page (without reverse merge)

- README.MD
- saltgui/static/scripts/output/output.js
- saltgui/static/scripts/output/outputSaltGuiHighstate.js
- saltgui/static/scripts/routes/job.js
- saltgui/static/scripts/routes/minions.js
- saltgui/static/scripts/routes/page.js
See #151 
Removal of nanoseconds in job start time does not bring any value and I think that can be removed.
> removal of nanoseconds in job start time

- saltgui/static/scripts/routes/keys.js
- saltgui/static/scripts/routes/minions.js
- saltgui/static/scripts/routes/page.js
> Cleanup page.js

- docker/conf/master
- saltgui/index.html
- saltgui/static/scripts/router.js
- saltgui/static/scripts/routes/page.js
- saltgui/static/scripts/routes/templates.js
- saltgui/static/stylesheets/page.css
> dedicated job template page

- saltgui/index.html
- saltgui/static/scripts/routes/grains.js
- saltgui/static/scripts/routes/grainsminion.js
- saltgui/static/scripts/routes/jobs.js
- saltgui/static/scripts/routes/page.js
- saltgui/static/scripts/routes/pillars.js
- saltgui/static/scripts/routes/pillarsminion.js
- saltgui/static/scripts/routes/schedules.js
- saltgui/static/scripts/routes/schedulesminion.js
- saltgui/static/scripts/routes/templates.js
closes https://github.com/erwindon/SaltGUI/issues/154
> Job details

- saltgui/index.html
- saltgui/static/scripts/routes/job.js
- saltgui/static/scripts/routes/page.js
- saltgui/static/scripts/routes/route.js
- saltgui/static/stylesheets/job.css
closes https://github.com/erwindon/SaltGUI/issues/141
> add ability to rerun the job

- README.MD
- saltgui/static/scripts/output/outputNested.js
- saltgui/static/scripts/output/outputYaml.js
- saltgui/static/scripts/routes/grains.js
- saltgui/static/scripts/routes/minions.js
- saltgui/static/stylesheets/grains.css
- tests/unit/output.js
> preview for selected grains

- saltgui/index.html
- saltgui/static/scripts/api.js
- saltgui/static/scripts/routes/keys.js
- saltgui/static/scripts/routes/page.js
closes: https://github.com/erwindon/SaltGUI/issues/159
closes: #115
> ux keys page improvments

- saltgui/index.html
- saltgui/static/scripts/dropdown.js
- saltgui/static/scripts/router.js
- saltgui/static/scripts/routes/page.js
- saltgui/static/scripts/routes/route.js
- saltgui/static/stylesheets/dropdown.css
- saltgui/static/stylesheets/main.css
- tests/functional/login.js
closes: https://github.com/erwindon/SaltGUI/issues/176
> fix top menu visibility for small screens

- saltgui/static/scripts/router.js
- saltgui/static/scripts/routes/job.js
- saltgui/static/scripts/routes/page.js
closes: https://github.com/erwindon/SaltGUI/issues/139
> closing job-details page should redirect to previous page

- docker/README.md
- docker/docker-compose.yml
- docker/dockerfiles/dockerfile-saltmaster
- docker/dockerfiles/dockerfile-saltminion-centos
- docker/dockerfiles/dockerfile-saltminion-debian
- docker/dockerfiles/dockerfile-saltminion-ubuntu
After merge new image must be published to docker hub.
> Update salt version to 2019.2.0

- saltgui/static/scripts/output/Output.js
- saltgui/static/scripts/output/OutputHighstate.js
- saltgui/static/scripts/output/OutputNested.js
fixes #134 
colours are added.
Only the colours from the states are taken into account. That means e.g. that syntax-colouring for the `Changes:` section is not available.
> Show original highstate output format

- saltgui/index.html
- saltgui/static/scripts/DropDown.js
- saltgui/static/scripts/Utils.js
- saltgui/static/scripts/routes/Grains.js
- saltgui/static/scripts/routes/GrainsMinion.js
- saltgui/static/scripts/routes/Jobs.js
- saltgui/static/scripts/routes/Keys.js
- saltgui/static/scripts/routes/Login.js
- saltgui/static/scripts/routes/Minions.js
- saltgui/static/scripts/routes/Page.js
- saltgui/static/scripts/routes/Pillars.js
- saltgui/static/scripts/routes/PillarsMinion.js
- saltgui/static/scripts/routes/Route.js
- saltgui/static/scripts/routes/Schedules.js
- saltgui/static/scripts/routes/SchedulesMinion.js
- saltgui/static/scripts/routes/Templates.js
- saltgui/static/stylesheets/page.css
- saltgui/static/stylesheets/tooltip.css
closes #180
closes #116
see #205
> Jobdetails

- saltgui/static/scripts/routes/Grains.js
- saltgui/static/scripts/routes/Minions.js
- saltgui/static/scripts/routes/Page.js
- saltgui/static/scripts/routes/Pillars.js
- saltgui/static/scripts/routes/Schedules.js
> Local IP addresses of Salt Minions are not being reflected correctly in the main page listing

- saltgui/index.html
- saltgui/static/scripts/Api.js
- saltgui/static/scripts/CommandBox.js
- saltgui/static/scripts/Router.js
- saltgui/static/scripts/routes/Beacons.js
- saltgui/static/scripts/routes/BeaconsMinion.js
- saltgui/static/scripts/routes/Page.js
- saltgui/static/scripts/routes/PillarsMinion.js
- saltgui/static/scripts/routes/Schedules.js
- saltgui/static/scripts/routes/SchedulesMinion.js
- saltgui/static/stylesheets/beacons.css
- saltgui/static/stylesheets/grains.css
- saltgui/static/stylesheets/keys.css
- saltgui/static/stylesheets/page.css
- saltgui/static/stylesheets/schedules.css
Implement a "beacons" screen.
Similar to pillars and/or schedules screen.
Allow zoom in on minion.
Allow manipulation of beacon definition.
> implement beacons

- saltgui/static/stylesheets/tooltip.css
> better background for tooltip on output panel

- saltgui/index.html
- saltgui/static/scripts/Api.js
- saltgui/static/scripts/Router.js
- saltgui/static/scripts/routes/Minions.js
- saltgui/static/scripts/routes/Options.js
- saltgui/static/scripts/routes/Route.js
- saltgui/static/stylesheets/main.css
- saltgui/static/stylesheets/options.css
- saltgui/static/stylesheets/page.css
Shows:
* items from the localStorage
* items from the sessionStorage
* items from the `master` file
Has the ability to adjust a few of the values so that their effect can be investigated without server restarts and/or bothering other users.
Page becomes visible when CTRL-clicking the SaltGUI logo in the top-left of the screen.
> Make a (hidden) page that shows the configuration

- saltgui/static/scripts/Api.js
- saltgui/static/scripts/CommandBox.js
- saltgui/static/scripts/Router.js
- saltgui/static/scripts/TargetType.js
- saltgui/static/scripts/Utils.js
- saltgui/static/scripts/output/Output.js
- saltgui/static/scripts/routes/Grains.js
- saltgui/static/scripts/routes/Login.js
- saltgui/static/scripts/routes/Options.js
- saltgui/static/scripts/routes/Page.js
- saltgui/static/scripts/routes/PillarsMinion.js
- saltgui/static/scripts/routes/Templates.js
> Empty the LOCAL storage on logout

- saltgui/static/scripts/CommandBox.js
- saltgui/static/stylesheets/main.css
> Tooltips that are near the border of the CommandBox are not shown properly

- saltgui/static/scripts/output/Output.js
- saltgui/static/scripts/output/OutputHighstate.js
- saltgui/static/scripts/output/OutputSaltGuiHighstate.js
> added support for orchestration output

- README.md
- saltgui/index.html
- saltgui/static/jsonpath/jsonpath-0.8.0.js
- saltgui/static/scripts/routes/Grains.js
> Allow more flexibility when showing preview of grains

- .gitignore
- README.md
- saltgui/static/scripts/Api.js
- saltgui/static/scripts/routes/Keys.js
> provide information wrt deleted minions and other situations

- README.md
- saltgui/static/scripts/Api.js
- saltgui/static/scripts/Router.js
- saltgui/static/scripts/config.js
- saltgui/static/scripts/output/Output.js
- saltgui/static/scripts/routes/Beacons.js
- saltgui/static/scripts/routes/BeaconsMinion.js
- saltgui/static/scripts/routes/Grains.js
- saltgui/static/scripts/routes/GrainsMinion.js
- saltgui/static/scripts/routes/Job.js
- saltgui/static/scripts/routes/Jobs.js
- saltgui/static/scripts/routes/Keys.js
- saltgui/static/scripts/routes/Login.js
- saltgui/static/scripts/routes/Minions.js
- saltgui/static/scripts/routes/Options.js
- saltgui/static/scripts/routes/Page.js
- saltgui/static/scripts/routes/Pillars.js
- saltgui/static/scripts/routes/PillarsMinion.js
- saltgui/static/scripts/routes/Route.js
- saltgui/static/scripts/routes/Schedules.js
- saltgui/static/scripts/routes/SchedulesMinion.js
- saltgui/static/scripts/routes/Templates.js
close #279 
Updated SaltGUI so that the pages can have a configurable prefix.
for history see #279
> url prefix fully configurable

- README.md
- saltgui/index.html
- saltgui/static/scripts/Api.js
- saltgui/static/scripts/Router.js
- saltgui/static/scripts/Utils.js
- saltgui/static/scripts/routes/Events.js
- saltgui/static/stylesheets/events.css
- saltgui/static/stylesheets/page.css
> addition of events viewer page

- saltgui/index.html
- saltgui/static/scripts/Character.js
- saltgui/static/scripts/CommandBox.js
- saltgui/static/scripts/Documentation.js
- saltgui/static/scripts/DropDown.js
- saltgui/static/scripts/Router.js
- saltgui/static/scripts/RunType.js
- saltgui/static/scripts/TargetType.js
- saltgui/static/scripts/Utils.js
- saltgui/static/scripts/output/Output.js
- saltgui/static/scripts/output/OutputHighstateTaskSaltGui.js
- saltgui/static/scripts/output/OutputNested.js
- saltgui/static/scripts/output/OutputYaml.js
- saltgui/static/scripts/panels/BeaconsMinion.js
- saltgui/static/scripts/panels/Events.js
- saltgui/static/scripts/panels/Jobs.js
- saltgui/static/scripts/panels/JobsDetails.js
- saltgui/static/scripts/panels/Keys.js
- saltgui/static/scripts/panels/Options.js
- saltgui/static/scripts/panels/Panel.js
- saltgui/static/scripts/panels/PillarsMinion.js
- saltgui/static/scripts/panels/Stats.js
- saltgui/static/sorttable/sorttable.js
- tests/unit/Output.test.js
preparation for #338
defines constants for each special character.
prefer js/java escape codes over html escape codes.
> Prepare code for centralized support for fonts/characters

- saltgui/static/scripts/Router.js
- saltgui/static/scripts/panels/Login.js
> Redirect to original URL parameters after login

- saltgui/static/scripts/panels/HighState.js
I would like a enhanced hightstate page on which we could define some display parameters.
the enhanced page would allow (at least) selection of the salt-commands to consider for the page :
- with the choice "state.highstate+state.apply" it would have the current functionality
- with the choice "state.highstate" it would be limited to that information only
- with the choice "state.apply" it would be limited to that information only
we only use "state.highstate" to define whether the server is in highstate or not, and "state.apply" is used only for deployment. So this new page could be very useful. 
see also : https://github.com/erwindon/SaltGUI/issues/458
> Enhanced Highstate page

- saltgui/static/scripts/Character.js
- saltgui/static/scripts/output/Output.js
- saltgui/static/scripts/panels/HighState.js
- saltgui/static/stylesheets/page.css
> update visualization for task-changed

- saltgui/static/scripts/panels/Keys.js
- saltgui/static/scripts/panels/Login.js
SaltStack 3007 introduced the "master-cluster" concept.
* Build a master-cluster based environment
* Test SaltGUI with the master-cluster
* Adjust where appropriate, e.g. to better show the configuration for that cluster
see also https://saltproject.io/blog/salt-release-3007-is-now-available/ and https://github.com/saltstack/salt/blob/3007.x/doc/topics/tutorials/master-cluster.rst and https://github.com/saltstack/salt-enhancement-proposals/blob/1433501a1417f78c895345a675e21a8b6382bb61/0000-master-cluster.md
> Add support for master-cluster
