saltgui/index.html
saltgui/static/scripts/api.js
saltgui/static/scripts/routes/home.js
saltgui/static/scripts/routes/job.js
saltgui/static/stylesheets/main.css

Currently, the "command" popup can be closed by clicking outside the "command" window.
Currently, the "job" popup can be closed by clicking on the "SaltGUI" logo.
I've added "close" buttons, in the same style of the logout button, to do the same.
The benefit is of course that the user sees these actions.

Added 'close' buttons on command+job windows

---

README.MD
saltgui/index.html
saltgui/static/scripts/api.js
saltgui/static/scripts/routes/login.js
saltgui/static/stylesheets/login.css
saltgui/static/stylesheets/main.css

Currently SaltGUI supports only PAM as authentication method.
This PR adds support for the other authentication methods.
A dropdown box is added to the login screen.
When nothing is entered, PAM is used as before.
The user's choice is persisted in the browser's local storage, so that on the next login, the default is usually already correct.
Regression tested with PAM implicitly selected. Tested with PAM explicitly selected. Tested also with AUTO, FILE, SHAREDSECRET and YUBICO.

Added support for generic EAUTH

---

saltgui/index.html
saltgui/static/scripts/routes/login.js

Added `mysql` as authentication method. It was tested with an actual mysql installation.
This one was not included in the previous PR on `pam` because it was a bit harder to test due to the additional setup.
Also disable the dropdown box just like use U/P fields.
Also retired `auto` and `sharedsecret` as these are (depending on actual use) a bit unsafe.
Btw, I see no reason to add further authentication methods at this moment.

Added mysql as authentication method and retired auto and sharedsecret

---

saltgui/static/scripts/routes/keys.js
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/page.js

The current SaltGUI adds the hostname internally to the list of grains that it has retrieved from a minion. That makes to very hard to distinguish the actual list of grains later for more dedicated functionality.
This PR stops adding the hostname to the list of grains and starts passing the hostname as a proper parameter.

do not add hostname as a grain

---

saltgui/static/scripts/router.js
saltgui/static/scripts/routes/keys.js
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/page.js
saltgui/static/scripts/utils.js

Some for-loops still use explicit indexing to access all list/array members, while the index itself is not used for anything else. In modern JS, this can be done in a more elegant way.
This PR converts all loops to more iteration-style loops.
e.g.
from:
`for(let i = 0; i < hostnames.length; i++) this._addMinion(list, hostnames[i]);`
to:
`for(const hostname of hostnames) this._addMinion(list, hostname);`

use only iterations instead of indexing

---

saltgui/static/scripts/routes/job.js
saltgui/static/scripts/routes/page.js

The jobs panel shows target+command+date, and not targettype. When zooming in on a job, the target is no longer shown. It is true that the list of minions is shown, but the information on how these were selected is no longer shown.
This PR shows the targettype+target in both the jobs panel (on pages "minions" and "keys"; and on the "job" page, which is reached after clicking on a job.
For simplicity, the words "glob" (the default) and "list" are suppressed.
Due to a bug in 2018.3, many jobs are stored as of type "list" while they were not. So that would have been the second reason not to show the indicator for targettype "list".

 show targettype+target on jobs panel and jobs page 

---

saltgui/static/scripts/output.js

In a recent PR, support for local documentation was added. In the conversion from the returned documentation to the presentation version, several markup features were applied. This still left a stray `_` character for external links, as well as a table of external links, each prefixed with the text `.. _`.
This PR recognized this situation and properly applies the link to the original text. The table of external links is now no longer visible.
This markup appears in e.g. `pkg.install`.

extension on documentation support: added external link support

---

saltgui/static/scripts/api.js
saltgui/static/scripts/routes/job.js
saltgui/static/scripts/routes/keys.js
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/page.js
saltgui/static/scripts/utils.js
tests/unit/utils.js

The jobs panel currently does not show any information about jobs that are still in progress. This PR adds the progress statistics for the jobs that are in progress. The number of running and the number of completed jobs is shown.
test with: start `salt '*' test.rand_sleep 300`. then refresh the SaltGUI screen.
note that this is static information, it is updated only on a screen refresh.
sample:
> ![afbeelding](https://user-images.githubusercontent.com/3663742/46039869-15d8cc80-c10f-11e8-9c38-9fbdcee1dcf5.png)

show progress of a long job

---

saltgui/static/scripts/output.js
tests/unit/output.js

When issuing the `grains.ls` command, its output is mistaken for documentation output.
The documentation detector (in `output.js`) did not test for an object to actually being an array.
Now it does, and a unit test was added to prove it.

fixed array output

---

saltgui/static/scripts/output.js
tests/unit/output.js

The new object formatter does not know how to handle a `null` value.
`null` is an object, but it is still quite different.
Replay with `test.echo null`
The new object formatter also did not know how to handle a `undefined` value.
It was passed to `JSON.stringify`, but that returns a `undefined` object instead of the string value `undefined`.
Not sure whether this can occur in real life.

null output was not supported

---

saltgui/index.html
saltgui/static/scripts/output.js
saltgui/static/scripts/routes/job.js
saltgui/static/stylesheets/main.css

SaltGUI shows job output in 2 places.
First is the direct output when running a command.
Second is the output produced by jobs, or from older commands.
A bit of tweaking is needed because the structure that contains the output is slightly different between commands and jobs.
Note that some of the additional details present in that structure are still ignored. This PR only handles the basic formatting and does not introduce showing new details.

apply new output format also to jobs output

---

saltgui/index.html
saltgui/static/scripts/commandbox.js
saltgui/static/scripts/documentation.js
saltgui/static/scripts/runtype.js
saltgui/static/scripts/targettype.js

Currently SaltGUI supports only `glob` style addresses as targets.
This PR allows the entry of other targettypes. Instead of supporting all targettypes, only `glob`, `list` and `compound` are now supported. With `compound` available, it is possible to effectively use all other targettypes. e.g. to target minions with a specific "grain" set, use `G@`, e.g. `G@os:CentOS`.
See also https://docs.saltstack.com/en/latest/topics/targeting/compound.html.
A dropdown control after the address field allows to select a different address type. But unless the user makes a selection there, the system will automatically choose `list` when the address contains at least one `,`. Or it will choose `compound` when the address contains at least one `@`, or any of `space`, `(` or `)`.

selectable+autodetect targettype

---

README.MD
saltgui/index.html
saltgui/static/scripts/api.js
saltgui/static/scripts/commandbox.js
saltgui/static/scripts/dropdown.js
saltgui/static/scripts/output.js
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/page.js
saltgui/static/scripts/targettype.js
saltgui/static/stylesheets/dropdown.css

This PR adds support for templates for the command-box.
As requested in #11.
Templates are maintained in the `master` file.
Values from the selected template are simply copied into the on-screen fields.

added support for command templates

---

README.MD
saltgui/index.html
saltgui/static/scripts/commandbox.js
saltgui/static/scripts/routes/page.js

As requested in #86 
Uses the html native feature `<datalist>`.
The list holds the minion names and the node-group names. The node-group names are prefixed with `#` for easy entry.
Note that both the minion list and the node-group list are updated asynchronously. So entries in the list may be available only a few seconds after start-up.

added autocomplete for minion or nodegroup entry

---

saltgui/static/scripts/api.js

SaltGUI verifies the validity of the login session.
However, it leaves a nasty looking (but harmless) error message when the user is not logged in.
That error is now suppressed.

ignore error from the login-session-check

---

saltgui/index.html
saltgui/static/scripts/commandbox.js
saltgui/static/scripts/routes/grainsminion.js
saltgui/static/scripts/routes/page.js

See #60 
*  edit grain
compose a `grains.setval` command to update the grain value. the command is ready-to-run, but usually the value is updated first by the user.
*   delete grain
compose a `grains.delkey` command to delete the grain. the command is ready-to-run
*   delete grain value
compose a `grains.delval` command to delete the grain value. this may have limited use next to the previous command. the command is ready-to-run
*   add item to grain
only available when the grain value is a list. compose a `grains.append` command. it is easier to use than the edit-grain function
*    delete item from grain
Chose to not implement this, due to fact that GUI would become messy

add a few simple commands for grains

---

saltgui/index.html
saltgui/static/scripts/commandbox.js
saltgui/static/scripts/routes/page.js
saltgui/static/scripts/routes/schedules.js
saltgui/static/scripts/routes/schedulesminion.js

See #61 
* run a job manually
compose a ready-to-run `schedule.run_job` command to start the selected schedule
* commands to enable/disable jobs
compose a ready-to-run `schedule.enable_job` or `schedule.disable_job` for the selected schedule
* commands to enable/disable scheduler
compose a ready-to-run `schedule.enable` or `schedule.disable` for the selected minion.
* command to delete a job
compose a ready-to-run `schedule.delete` command for the selected schedule
* commands to edit a job
compose a `schedule.modify` command for the selected schedule. all displayed parameters are pre-filled in the command

add a few simple commands for schedules

---

docker/conf/master

See #97 
The docker images contained a more restrictive `master` file than what was advertised in the documentation in `README.MD`.

Fix authentication failures for some commands when using docker

---

README.MD
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/pillarsminion.js

See also #100 
It is now possible to mark a list of pillar name pattern to indicate that these do not hold sensitive information. The pillars matching these patterns are initially shown. All others are initially hidden as before.

improvement for pillar information are not always secret 

---

saltgui/static/stylesheets/page.css

See #118 
Solved by removing the `user-select: none` clauses from CSS.
@dawidmalina can you verify that this now works properly?

removed css that prevented copy2clip to work

---

saltgui/static/scripts/routes/page.js

See #117
The selection of the IP number has changed from "first-from-the-list" to:
1) Use the first public IP number when one is available. This excludes the 3 known private ranges (10.x.x.x/8, 192.168.x.x/16 and 172.16.x.x/12) and the local range (127.x.x.x/8).
2) Use the first external IP number when one is available.
3) Return the first from the list, which should then be a 127.x.x.x number

find the best IP number to show

---

docker/srv/salt/install-packages.sls
docker/srv/salt/top.sls
docker/srv/salt/vim/init.sls
docker/srv/salt/vim/map.jinja

CentOS package name is different and highstate failed:
```
local:
----------
ID: requirements
Function: pkg.installed
Result: False
Comment: The following packages failed to install/update: vim
Started: 21:37:56.588012
Duration: 9044.587 ms
Changes:
Summary for local
------------
Succeeded: 0
Failed:    1
```

Fix package name for centos

---

saltgui/static/scripts/routes/grains.js
saltgui/static/scripts/routes/grainsminion.js
saltgui/static/scripts/routes/keys.js
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/page.js
saltgui/static/scripts/routes/pillars.js
saltgui/static/scripts/routes/pillarsminion.js
saltgui/static/scripts/routes/schedules.js
saltgui/static/scripts/routes/schedulesminion.js
saltgui/static/stylesheets/pillars.css

closes #113:
On most pages, a dropdown menu exists per minion.
It is made visible when all information for the minion has been retrieved.
That is not always useful.
On the Keys page, it should be possible to reject/delete a key before that information is present.
On the Grains/Schedules/Pillars pages, it should be possible to zoom in to a specific minion before that information is present. User may select an unresponsive minion. But it is always a risk that a minion becomes unresponsive in the mean time.
Additionally:
Menu item "`Job details`" should not contain `...`
Additionally:
Show minion name in title of grains-details, schedule-details and pillar-details earlier.

dropdown menu not immediatelly visible

---

saltgui/static/scripts/output/outputDocumentation.js
saltgui/static/scripts/routes/job.js

Adding more menu items on the job details menu, with:
* redo all jobs that did not have a response, not visible when n/a
* redo all jobs that had an error, not visible when n/a
* these 2 together, not visible when n/a
* redo all but replacing the original pattern with the explicit list of minions, al;ways there

add more retry options

---

saltgui/index.html
saltgui/static/scripts/routes/grains.js
saltgui/static/scripts/routes/grainsminion.js
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/page.js
saltgui/static/scripts/routes/pillars.js
saltgui/static/scripts/routes/schedules.js
saltgui/static/scripts/routes/schedulesminion.js
saltgui/static/scripts/routes/templates.js
saltgui/static/stylesheets/page.css

closes #148
Several menu items exist for which the only action is to show more details.
That action should also be implemented by highlighting the line with `whitesmoke` background (see jobs list in secondary panel). Clicking on the line should navigate to the details.
A menu item for this should remain.
This is already implemented in the jobs panel. But the jobs panel is lacking a popup menu. That should be added.
The following actions should be realised:
*  `jobs` (panel) --> `Show details...` (and add menu to do that also)
* `minions` --> `Apply state...`
* `keys` --> NONE
* `grains` --> `Show grains`
* `grains (details)` --> `Edit grain...`
* `schedules` --> `Show schedules`
* `schedules (details)` --> `Modify job...`
* `pillars` --> `Show pillars`
* `pillars (details)` --> show/hide …

easier navigation to details 

---

saltgui/index.html
saltgui/static/stylesheets/keys.css
saltgui/static/stylesheets/page.css
saltgui/static/stylesheets/schedules.css

Currently, keys are shown in a proportional font on the Keys page.
This looks slightly chaotic.
This PR sets a monospace font only for that column.

show keys with monospace font

---

saltgui/static/scripts/api.js
saltgui/static/scripts/routes/grains.js
saltgui/static/scripts/routes/grainsminion.js
saltgui/static/scripts/routes/job.js
saltgui/static/scripts/routes/jobs.js
saltgui/static/scripts/routes/keys.js
saltgui/static/scripts/routes/minions.js
saltgui/static/scripts/routes/pillars.js
saltgui/static/scripts/routes/pillarsminion.js
saltgui/static/scripts/routes/schedules.js
saltgui/static/scripts/routes/schedulesminion.js
saltgui/static/scripts/routes/templates.js

for #182 and other reasons, the api functions must be sanitized:
* only use the direct api functions (prevents name conflicts)
* rename all api functions according to the api function that they are calling
* organize the api functions alphabetically
closes #182

always use the regular api

---

.gitignore
package.json
runtests.sh

Yarn has a calling home feature and sends statistics to Facebook. Not sure but in EU it could be against privacy law. Furthermore NPM got more and more stable the last years. I would like to go back to NPM to be as close as possible to the NodeJS stack and reduce usage of external tools.
Should be easily doable: Small fixes in package.json, runtests,sh and remove yarn's lockfile which will be exchanged with native package-lock.json
**Describe alternatives you've considered**
For now I see no alternatives.

switch to npm PART 1

---

saltgui/static/scripts/output/Output.js
saltgui/static/scripts/routes/Job.js
saltgui/static/scripts/routes/Keys.js
saltgui/static/stylesheets/page.css

closes #206
When job details are shown, all minions without data are treated equally. It is assumed that the job has timed out. This a result of the usage of call jobs.list_job.
But the jobs overview(s) already show how many minions are still working on a job.
Use function jobs.active provides the difference between minions that timed out and minions that are still working on the request.

Use jobs.active to show which output is still expected

---

docs/PERMISSIONS.md
saltgui/static/scripts/Api.js
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Documentation.js
saltgui/static/scripts/Utils.js
saltgui/static/scripts/output/Output.js
saltgui/static/scripts/routes/Grains.js
saltgui/static/scripts/routes/GrainsMinion.js
saltgui/static/scripts/routes/Job.js
saltgui/static/scripts/routes/Jobs.js
saltgui/static/scripts/routes/Keys.js
saltgui/static/scripts/routes/Minions.js
saltgui/static/scripts/routes/Page.js
saltgui/static/scripts/routes/Pillars.js
saltgui/static/scripts/routes/PillarsMinion.js
saltgui/static/scripts/routes/Schedules.js
saltgui/static/scripts/routes/SchedulesMinion.js
saltgui/static/scripts/routes/Templates.js

closes #195 
Problems:
* code involving promises looks bad
* code involving promises uses its own administration (e.g. `keysLoaded`)
* promises are used in multiple layers
* sequence of promises is not guaranteed
Work done:
* Once created, each promise is first created as a constant with a standardized name
* no extra promise layer is used
* sequence of promises is now managed
* extra administration is removed
* added error handling for technical errors from normal salt commands
* added error handling for technical errors from RUNNER salt commands
* added error handling for technical errors from WHEEL salt commands
TODO:
* only allow tooltips from SPANs, not from TDs

Rework on promise creations/executions

---

saltgui/index.html
saltgui/static/hilitor/hilitor.js
saltgui/static/scripts/Utils.js
saltgui/static/scripts/routes/Grains.js
saltgui/static/scripts/routes/GrainsMinion.js
saltgui/static/scripts/routes/Keys.js
saltgui/static/scripts/routes/Minions.js
saltgui/static/scripts/routes/Page.js
saltgui/static/scripts/routes/Pillars.js
saltgui/static/scripts/routes/PillarsMinion.js
saltgui/static/scripts/routes/Schedules.js
saltgui/static/scripts/routes/SchedulesMinion.js
saltgui/static/scripts/routes/Templates.js
saltgui/static/stylesheets/main.css
saltgui/static/stylesheets/page.css

Depending on the environment, the pages may get a bit long.
A search box is added. The table will then only show the rows that somehow contain this text.
e.g.:
Done:
* add facility to hide/show the search boxes. initially not shown.
* fix search facility on pillar-details screen, which has some problems
* added facility to highlight the found text
* are the job list first (A) "length restricted THEN searchable" or should they be (B) "searchable and then length restricted". Currently (A) applies. (B) may be more useful. ==> the current situation (A) remains. We probably will do (B) later.

add table search function

---

README.md
saltgui/static/scripts/routes/Minions.js
saltgui/static/scripts/routes/Page.js

closes #223 
Allow the user to configure additional jobs that will be hidden.
And allow the user to configure jobs that will be shown when otherwise hidden.
See file `README.md` for more details.

allow additional control over which jobs are shown/hidden

---

saltgui/index.html
saltgui/static/scripts/Api.js
saltgui/static/scripts/routes/BeaconsMinion.js
saltgui/static/stylesheets/beacons.css

closes #225 
The current system shows the definitions of the beacons on each minion.
But the beacon values are available on the event bus.
The proposal is to listen for the specific event messages,
When a match is found for a minion+beacon, display the value on screen.
Any previous value is overwritten.
User must have patience until the first beacon is seen.

show beacon values

---

saltgui/index.html
saltgui/static/scripts/Api.js
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Router.js
saltgui/static/scripts/Utils.js
saltgui/static/scripts/routes/BeaconsMinion.js
saltgui/static/scripts/routes/Keys.js
saltgui/static/sorttable/sorttable.js
saltgui/static/stylesheets/tooltip.css

SaltGUI uses screen refreshes after many actions, This takes time on both client and server.
Implement asynchronous updates. SaltGUI can subscribe to the relevant message streams. The messages that are received can be used to update the screen.
Use /events to subscribe to all events.
This PR provides an update for the KEYS screen. Any action on a KEY now results in a live update of this screen. It does not matter whether the update originated from SaltGUI or not.

asynchronous updates for KEYS

---

saltgui/static/scripts/output/Output.js
saltgui/static/scripts/output/OutputJson.js
tests/unit/Output.test.js

When simple objects are shown in a job output, the output can still be on one line.
Currently objects and arrays are always shown as multi-line.
Show short objects and arrays as one line.

allow simple objects on one line

---

saltgui/static/scripts/routes/Page.js

closes #253 
Solution is to use the original element reference instead of the mouse-event-target, as this may be on a child element (the tooltip bubble).

Clicking on tooltip "click to copy" copies that text instead of the target text

---

saltgui/static/scripts/DropDown.js
saltgui/static/scripts/routes/Job.js
saltgui/static/stylesheets/dropdown.css

closes #219 
When viewing job, 4 links are shown for each running process within that job.
The titles are `info`, `term`, `kill` and `signal`
These links are now organized in a drop-down menu.
The titles should be `Show process info`, `Terminate process`, `Kill process` and `Signal process`

actions for jobs now in dropdown

---

saltgui/index.html
saltgui/static/stylesheets/main.css

Problem:
The current run-button is built from the text `>_`, which is given an html-border.
That border is relatively thick and seems to form a circle.
However, it is not a circle as it is just a border around `>_`.
It looks like:
Solution:
Style the run-button as SVG
It now looks like:

make the cmd-run button a true circle

---

saltgui/static/scripts/Api.js
saltgui/static/scripts/DropDown.js
saltgui/static/scripts/Router.js
saltgui/static/scripts/Utils.js
saltgui/static/scripts/output/Output.js
saltgui/static/scripts/pages/Logout.js
saltgui/static/scripts/pages/Page.js
saltgui/static/scripts/panels/Beacons.js
saltgui/static/scripts/panels/BeaconsMinion.js
saltgui/static/scripts/panels/Grains.js
saltgui/static/scripts/panels/GrainsMinion.js
saltgui/static/scripts/panels/Job.js
saltgui/static/scripts/panels/JobsDetails.js
saltgui/static/scripts/panels/JobsSummary.js
saltgui/static/scripts/panels/Keys.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/scripts/panels/Pillars.js
saltgui/static/scripts/panels/PillarsMinion.js
saltgui/static/scripts/panels/Schedules.js
saltgui/static/scripts/panels/SchedulesMinion.js

This PR turns SaltGUI into a single-page web application.
Navigation is no longer between web-pages, but between states.
Don't worry, the states act as pages.
benefits:
* navigation is faster
* navigation has nice page transitions
* the back-button should now always work properly
* there is only one type of navigation
This may also solve one or more of #229, #293, #327.
This obsoletes #334.

Singlepage

---

saltgui/static/scripts/Api.js
saltgui/static/scripts/panels/Minions.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/stylesheets/page.css

use the `wheel.minions.connected` function to quickly determine the on-line minions. The other minions as reported by `wheel.key.list_all` are thus offline. This helps on the main screen because otherwise the off-line status is only known once `grains.items` returns. And with offline minions present, that may take several seconds.

use salt-api to determine connected minions

---

README.md
saltgui/index.html
saltgui/static/scripts/Router.js
saltgui/static/scripts/pages/Minions.js
saltgui/static/scripts/pages/Page.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Reactors.js
saltgui/static/scripts/panels/Templates.js

I would like to allow some people in our team to access SaltGUI to run salt commands on the minions they are allowed to control, and it would be great to be able to hide the tabs they won't use.
The best solution would be to have a way to configure which pages a user is allowed to see (maybe through extra configuration in the salt-master config like this is currently done for the templates feature), then based on this user config, SaltGUI could hide the pages that the user is not allowed to see.

Add support for configuring which pages are displayed on SaltGUI

---

saltgui/static/scripts/Utils.js
saltgui/static/scripts/panels/Job.js
saltgui/static/scripts/panels/Jobs.js
saltgui/static/scripts/panels/JobsDetails.js

When viewing a job that has not completely finished, one can click on the first few words from the output to refresh the screen. this refreshed the whole screen.
Refresh only the output area without reloading the page.
See also #346.

refresh job without reload

---

saltgui/index.html
saltgui/static/scripts/Character.js
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/DropDown.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/stylesheets/dropdown.css
saltgui/static/stylesheets/events.css
saltgui/static/stylesheets/main.css

buttons have poor layout: the spacing is ad-hoc
buttons have poor visibility: the button image is usually a visual character so that the active area is unclear
This PR creates a grey background colour for each button.
This immediately makes the layout problem more visible, so the layout instructions are re-worked.

enhance visibility and layout of buttons

---

.gitignore
README.md
saltgui/static/scripts/Api.js
saltgui/static/scripts/panels/Login.js

In #367, @hoaivan requests the addition of auth method `sharedsecred`.
However, that is not a safe mechanism unless additional measures are taken to prevent leaking these credentials.
Therefore `sharedsecret` will not be added as a standard option in the login screen.
But here is an alternative...
A file `salt-auth.txt` can be placed on the server, which contains all of the additional auth methods that should be shown.
So additional options will only be visible when they are added to that file.
And also, any other auth mechanism can be made selectable.
Note that an auth method does not work unless it is also configured in the `master` file.
This PR replaces the original PR #367.

add support for additional salt.auth types

---

.gitignore
README.md
saltgui/index.html
saltgui/static/scripts/Api.js
saltgui/static/scripts/pages/Page.js
saltgui/static/scripts/panels/Login.js
saltgui/static/stylesheets/login.css

must support both TXT and HTML
content is different before and after login because after login, content may contain sensitive information (still not recommended though).
content before login is retrieved from a static file.
content after login is retrieved from the master file (which is unavailable before login)

show message-of-the-day during login and after login

---

README.md
saltgui/index.html
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Documentation.js

Button to show "custom command help", which is defined in salt master configuration
I very much like the command help from the '?' button.
Similarly, I want to be able to provide my own command help, with commands that we use frequently.
I know there are command templates. However, I wanted to provide a more general help.
- There is now a new button to show custom help text in the run-command-overlay
- Clicking the button fetches the salt config and creates the help text from config element `saltgui_custom_command_help`
- Note that it is also possible to provide other help here, not necessarily related to commands.
For example, the following config:
```
saltgui_custom_command_help: |
<h2>Job Commands</h2>
runners.jobs.active
=> Show active jobs
runners.jobs.list_job «JID»
=> Show job with …
```

custom command help

---

README.md
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Documentation.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Options.js

See also #432, which had technical problems
this is an exact re-implementation

custom command help - part deux

---

saltgui/static/scripts/issues/State.js

Removed minions are still in the issues panel
**To Reproduce**
1. add a minion.
2. accept its key
3. run highstate. Make it fail. (other failed state may work as well. haven't tested that)
4. remove minion
5. open issues tab. Minion still mentioned there as failed.
**Expected behavior**
The minion is gone. I expect it to be gone everywhere :)
If it's just a matter of time before it's erased then there's not really an issue so just close it then.
This issue was re-created from #439, which was accidentally connected to the wrong git branch...

removed minions still show up in issues tab (recreated)

---

saltgui/static/scripts/Character.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/stylesheets/page.css

Hello,
I am using the separate SaltGUI (1.28.0) solution in a nginx container (nginx:1.21.6).
Everything works fine but I have a problem with the hightstate page:
I have a lot of minions and states, and in the highstate page, the result of the highstate is far too long:
Is it possible to have only the final result with one circle ? and the detail if we click on the green/yellow/red circle ?
or another proper solution to reduce the result ?
I already tried this solution: https://github.com/erwindon/SaltGUI#performance, but I didn't see any change, maybe because I use a separate SaltGUI or maybe its not related with.
Screenshots
thanks a lot

Add the possibility to collapse the result of the states in the hightstate

---

saltgui/static/scripts/Api.js
saltgui/static/scripts/pages/Keys.js
saltgui/static/scripts/panels/Keys.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Minions.js
saltgui/static/scripts/panels/Panel.js

When salt-syndic is in use, there is a difference between the list of keys and the list of minions.
Since the list of keys is then shorter, the user may have the feeling that keys are missing.
When salt-syndic is in use, show a warning about the possible limited list of keys.
solution is to read configuration from master file
(previous solution mentioned reacting on specific salt-events)

syndic: add warning to Keys screen when syndic is in use

---

docs/README.md
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Documentation.js
saltgui/static/scripts/Utils.js
saltgui/static/scripts/output/Output.js
saltgui/static/scripts/panels/Grains.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/scripts/panels/Jobs.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Options.js
saltgui/static/scripts/panels/PillarsMinion.js

Hello,
it's not a bug, but questions or improvements.
I am using the separate SaltGUI (1.28.0) solution in a nginx container (nginx:1.21.6). 
Everything works fine but I have 2 problems with the hightstate page:
1) my saltstack master uses a Gitlab as a backend, so to deploy a specific branch with salt, I use this command on the host as an example: `salt-call state.apply saltenv=XXX pillarenv=XXX test=true`  (XXX = git branch)
The problem is that the result of the command will also be displayed on the saltgui hightstate page, but we should only see the results of the master branch and not the result of my XXX branch, because only the master branch is important to define if the server is in highstate or not.
Is it possible to hide these parasitic results in order to keep only the results …

ignore some jobs on highstate page

---

docs/README.md
saltgui/static/scripts/output/Output.js

Salt-master 3005.1 on Ubuntu 20.04, UI shows "Invalid.731210 Date" as and example for all the start times.
Here is the output from the master's console for ```salt '*' state.apply```
```
octopi:
----------
ID: timezone_packages
Function: pkg.installed
Name: tzdata
Result: True
Comment: All specified packages are already installed
Started: 12:09:31.983339
Duration: 274.309 ms
Changes:
----------
ID: dbus_for_timezone
Function: pkg.installed
Name: dbus
Result: True
Comment: All specified packages are already installed
Started: 12:09:32.258763
Duration: 88.489 ms
Changes:
----------
ID: dbus_for_timezone
Function: service.running
Name: dbus
Result: True
Comment: The service dbus is already running
Started: 12:09:32.356435
Duration: 189.594 ms
Changes:
----------
ID: …
```

Invalid Date showing with salt 3005.1

---

saltgui/static/scripts/output/Output.js
saltgui/static/scripts/output/OutputHighstate.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Options.js
saltgui/static/stylesheets/main.css

Saltstack recently introduced parameter `state_compress_ids`.
This will change the output for some output models
Let SaltGUI adjust the output in the same way.
See also https://docs.saltproject.io/en/latest/ref/output/all/salt.output.highstate.html
sample output (`state_compress_ids=false`):
```
salt-minion-1:
Name: apache-2 xyz - Function: cmd.run - Result: Changed Started: - 01:30:40.995510 Duration: 6.268 ms
Name: apache-2 xyz - Function: cmd.run - Result: Failed Started: - 01:30:41.019488 Duration: 7.277 ms
Name: apache-2 xyz - Function: cmd.run - Result: Changed Started: - 01:30:41.045495 Duration: 6.882 ms
Name: apache-2 xyz - Function: cmd.run - Result: Failed Started: - …
```

add support for parameter 'state_compress_ids'

---

saltgui/static/scripts/output/Output.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/stylesheets/page.css

When viewing the results from minion state jobs we see errors (red) and successes (green). I'd also like to see changes (blue).
Adding changes with blue colors instead of success that are currently green.
**Describe alternatives you've considered**
I am open for discussion!
Here are some pictures of what I see
This is from the jobs -> highstate ui. I'd also like to see the changes listed (in blue?)
This is from the jobs tab. Again would like to see changes as well. I am also note sure what the red (2) is as there is only one minion with one error in the states?
This is from a detailed look at the state. You can see you do show green (for successful) and blue (for …

Show changes on colored state reports

---

docs/README.md
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/output/Output.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Options.js

Some commands return only very simple information, like true/false. This is indistinguishable from the return of `false` on a timeout.
The API should use `full_return` as much as possible. The response from that clearly indicates success/failure as well as a separate result.
Update: while the data is better separated from the meta-data, it does not indicate success/failure. instead, it provided a result-code separate from the results. but the indication for success/failure is still missing.
Update: this is only relevant for free-format commands, not for the internal commands. When internal commands fail we don't show much extra information anyway.
Update: this must be arranged as a …

should always use full_return

---

saltgui/static/scripts/Router.js
saltgui/static/scripts/output/Output.js

As seen in the attached screenshot below (done on Firefox on Windows Server 2019), the timestamp in the white below the job name shows 1:24 EDT, while the output within the black output shows the timestamp as 9:24 EDT.  That matches the 4 hour difference that EDT applies to UTC (UTC-4).
**Screenshots**
New issue stemming out of testing for #485

Timezone conversion issues 

---

saltgui/static/scripts/output/Output.js

when retrieving the output from an API call before any results are available leads to an error message about variable `pMinionResponse` in `Output.js(508)`.
replay with something like `salt --async '*' test.sleep 60` and looking at the details for that job within those 60 seconds.

prevent problem showing output with output from 0 minions

---

docs/README.md
saltgui/static/scripts/Api.js
saltgui/static/scripts/Character.js
saltgui/static/scripts/Router.js
saltgui/static/scripts/pages/Nodegroups.js
saltgui/static/scripts/panels/BeaconsMinion.js
saltgui/static/scripts/panels/Nodegroups.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/stylesheets/page.css

Hello! In /etc/salt/master added block with nodegroups:
Is it possible to display nodegroups ("sandbox") in SaltGUI on the page with minions?

Ability to display nodegroups

---

saltgui/static/scripts/panels/Grains.js

current readme says 
saltgui_preview_grains:
- "osrelease_info"
single and double quotes both did not work.
commit #166 where that was adding has no quotes. which worked for me.
saltgui_preview_grains:
- osrelease_info
may want to update so others dont bang their head as much :)

Readme may be incorrect for grains

---

saltgui/static/scripts/pages/Logout.js
saltgui/static/scripts/panels/Stats.js

A bug in SaltStack itself...
When switching on `collect_stats` for salt-api, the call `/stats` fails with an internal server error response (code 500).
this happens at least for salt-versions up to 3006.1, which is the lasted at this moment. 
SaltGUI logs-out on any error from this call.
**Expected behaviour**
SaltGUI should ignore this specific error since it does not actually provide information on the login status.

collect_stats=true always causes a forced logout

---

saltgui/static/scripts/Utils.js
saltgui/static/scripts/issues/Issues.js
saltgui/static/scripts/panels/Beacons.js
saltgui/static/scripts/panels/BeaconsMinion.js
saltgui/static/scripts/panels/Events.js
saltgui/static/scripts/panels/Grains.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/scripts/panels/Issues.js
saltgui/static/scripts/panels/Jobs.js
saltgui/static/scripts/panels/Keys.js
saltgui/static/scripts/panels/Minions.js
saltgui/static/scripts/panels/Nodegroups.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/scripts/panels/Pillars.js
saltgui/static/scripts/panels/Schedules.js
saltgui/static/scripts/panels/Templates.js

function `setMsg` sets the status line at the bottom of a panel.
most (or all) of the panels that display a list of minions effectively call the function twice.
once from a specific function for that panel, and once from a common location.
but the common location only mentions the number of minions and thus hides the additional details that were set by that panel.
(but currently none of the panels add details, so the effect is limited)
**To Reproduce**
Cannot reproduce with current version.
See PR #515
show page "nodegroups"
the status line should mention the number of nodes and the number of nodegroups.
but that is quickly overwritten by the common function.
**Expected behaviour**
Status line should be determined in only one code location.
This …

setMsg is called multiple times for one page

---

saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/output/Output.js
saltgui/static/scripts/panels/Job.js

some salt command have long arguments lists.
the full argument list was used as the title of the Job page.
this should be shortened to the first 50 characters only.
but when that title is shortened, there is no more insight in the argument list of the command.
therefore, in that case, add the full command at the top of the output panel.

prevent problems with long job argument list

---

saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Utils.js

the command-box can be dismissed by typing ESC while the focus is in the TARGET or COMMAND fields.
but not when the focus is elsewhere, e.g. after clicking "Run Command"
Accept ESC also when focus is elsewhere

use ESC to close the command-box

---

docs/README.md
saltgui/static/scripts/panels/Grains.js

In the Grains page, additional columns can be added based on selected grain information.
Currently, the title of such column is always the same as the grain-name and/or grain-expression.
Specifically the grain-expression can be a bit complicated and distracting.
Add possibility to add own title to a custom-grain column.

allow custom title for the custom-grains

---

docs/README.md
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Panel.js

Converted saltgui_ipnumber_prefix to array for make possible set several ip prefixes from different networks

Converted saltgui_ipnumber_prefix to array

---

saltgui/index.html
saltgui/static/scripts/Router.js
saltgui/static/scripts/panels/Options.js
saltgui/static/stylesheets/tooltip.css

I takes time to scroll on SaltGui even if most of the state_id have not been updated on the minions.
It could be great to be able to have a toggle in order not to show state_ids that have not been updated.
**Describe alternatives you've considered**
Keep scrolling
We use SaltGui to manage dozens of minions, each made of os dozens of state_ids :)

Filter to show only changes for highstates

---

docs/README.md
saltgui/index.html
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Router.js
saltgui/static/scripts/Utils.js
saltgui/static/scripts/pages/Page.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/scripts/panels/Templates.js
saltgui/static/stylesheets/main.css
saltgui/static/stylesheets/tooltip.css

In addition to clicking to [X] on the Manual Run modal window, it would be great to have the same effect by pressing the ESC key. Also, on the main page, some keyboard shortcuts could make tasks easier. For example:
- "r" for opening the Manual Run modal
- "m" for minions
- ...and so on.
- "t" for templates. on this page, "1", "2", "3" etc. could apply the relevant template

feature request: keyboard shortcuts, ESC key

---

docs/README.md
saltgui/static/scripts/Api.js
saltgui/static/scripts/panels/Grains.js
saltgui/static/scripts/panels/GrainsMinion.js
saltgui/static/scripts/panels/Jobs.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Minions.js
saltgui/static/scripts/panels/Nodegroups.js
saltgui/static/scripts/panels/Options.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/scripts/panels/Pillars.js
saltgui/static/scripts/panels/PillarsMinion.js

Hi,
When doing some research on why i never get cached minion data on SaltGUI i discovered https://github.com/erwindon/SaltGUI/issues/538 which mentions there is a need for a database, however i found another possible solution:
Instead of using a Backend-Database to display some inventory/stored grains data of minions it should be possible to use the cache.grains function as documented in https://docs.saltproject.io/en/latest/topics/cache/index.html it looks like this cache also supports multiple backends/modules, see https://docs.saltproject.io/en/latest/ref/cache/all/index.html#all-salt-cache for a list so the database question is also answered.
It looks like implementing this could be really easy, actually a config-file option which exchanges the "normal grains command" with the …

use cache.grains function to display inventory data

---

docs/README.md
saltgui/static/scripts/panels/HighState.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Options.js

With a large number of salt minions, it is not enough to display only the last 10 highstates. I suggest leaving the default value 10 but adding the ability to change it through the config. I would also like to be able to customize the number of states for detailed display (default is 20)

add "saltgui_max_show_highstates" and "saltgui_max_highstate_states" in config options

---

saltgui/static/scripts/panels/Beacons.js
saltgui/static/scripts/panels/BeaconsMinion.js
saltgui/static/scripts/panels/Grains.js
saltgui/static/scripts/panels/GrainsMinion.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/scripts/panels/Issues.js
saltgui/static/scripts/panels/JobsDetails.js
saltgui/static/scripts/panels/JobsSummary.js
saltgui/static/scripts/panels/Minions.js
saltgui/static/scripts/panels/Nodegroups.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/scripts/panels/Pillars.js
saltgui/static/scripts/panels/Schedules.js
saltgui/static/scripts/panels/SchedulesMinion.js
saltgui/static/scripts/panels/Templates.js

clicking on table row has various effects: it may navigate to a details page or it may show the cmd-popup.
for menu items it is less obvious since the description already gives a clue and the "..." shows that a popup will be used.
with the introduction of #574 that becomes less obvious
add a i-icon to each table to show what will happen when you click on a row of that table.
see #574

add a navigation indicator for table rows

---

saltgui/static/scripts/panels/Beacons.js
saltgui/static/scripts/panels/BeaconsMinion.js
saltgui/static/scripts/panels/Grains.js
saltgui/static/scripts/panels/GrainsMinion.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/scripts/panels/JobsDetails.js
saltgui/static/scripts/panels/JobsSummary.js
saltgui/static/scripts/panels/Keys.js
saltgui/static/scripts/panels/Minions.js
saltgui/static/scripts/panels/Nodegroups.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/scripts/panels/Pillars.js
saltgui/static/scripts/panels/Schedules.js
saltgui/static/scripts/panels/SchedulesMinion.js
saltgui/static/scripts/panels/Templates.js

in-table dropdown menus currently are mostly at the end of the row. Unless a potentially big last column is present, in which case the menu is moved one column to the second-to last position (possibly third-to-last, etc).
for task items, often the dropdown menu is off-window
Move all in-table dropdown menus to the start of their row.
This also improves consistency...

move all in-table menu-items to the first column

---

saltgui/static/scripts/Character.js
saltgui/static/scripts/output/Output.js
saltgui/static/scripts/output/OutputHighstate.js
saltgui/static/scripts/output/OutputHighstateSummaryOriginal.js
saltgui/static/scripts/output/OutputHighstateTaskSaltGui.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/stylesheets/page.css

I suggest changing the task-changed display color for better readability of states

change color for changed tasks (before not different from not-changed)

---

saltgui/static/scripts/DropDown.js
saltgui/static/scripts/Utils.js
saltgui/static/scripts/issues/Issues.js
saltgui/static/scripts/panels/BeaconsMinion.js
saltgui/static/scripts/panels/GrainsMinion.js
saltgui/static/scripts/panels/Job.js
saltgui/static/scripts/panels/JobsDetails.js
saltgui/static/scripts/panels/JobsSummary.js
saltgui/static/scripts/panels/Nodegroups.js
saltgui/static/scripts/panels/Panel.js
saltgui/static/scripts/panels/SchedulesMinion.js
saltgui/static/scripts/panels/Templates.js
saltgui/static/stylesheets/main.css

I find it annoying when I'm waiting for a state/highstate to complete but all I get is a little reload icon color to see if it's done.
I think the arrow icon should rotate or be animated when running and then, instead of changing to green or red based on the result, it should simply display the output automatically without having to click on it...
**Describe alternatives you've considered**
Any kind of animated icon that shows it is still in progress, but for showing the output, I don't see why it wouldn't be that way. There is a callback making the icon change color so it should probably be simple enough to make the call to show the output. Something that is always wanted.
It could be …

Showing output automatically upon completion and animated icon

---

saltgui/static/stylesheets/grains.css

Will be really nice to have better visualization of grains that contain list of values (strings), for example:
```
salt-master:
- salt-master
- salt-minion
```
```
salt-master-custom.conf:
...
saltgui_preview_grains:
- Roles=roles    
- Roles2=$.roles.[*]
- Roles3=$.roles[*]
```
Instead:
```
[
"salt-master",
"salt-minion"
]
```
will be nice to have a list separated by `\n` I guess (without brackets and quotes):
```
salt-master
salt-minion
```

saltgui_preview_grains: Improvement

---

TODO.txt
docs/README.md
saltgui/static/scripts/Api.js
saltgui/static/scripts/Router.js
saltgui/static/scripts/output/Output.js
saltgui/static/scripts/output/OutputHighstate.js
saltgui/static/scripts/pages/Orchestrations.js
saltgui/static/scripts/panels/Job.js
saltgui/static/scripts/panels/Jobs.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Orchestrations.js

orchestrations are similar to highstates.
difference is that highstates are applied to individual minions (possibly multiple at the same time),
but orchestrations are schemes that coordinate work across minions.
this PR makes it possible to:
* view the defined orchestrations with their steps and the details of these steps; and
* start the execution of an orchestration; and
* display the outcome of an orchestration.
note that unlike highstates, SaltStack does not allow tracking an orchestration step-by-step. the system just does not generate any useful events for this.
note that the orchestrations page is only visible when there is at least one orchestration defined in the system.
please feel free to try out this feature before it is merged into SaltGUI.
comments and suggestions are …

add support for orchestrations

---

saltgui/static/scripts/issues/State.js
saltgui/static/scripts/pages/HighState.js
saltgui/static/scripts/pages/Issues.js
saltgui/static/scripts/pages/Job.js
saltgui/static/scripts/pages/Jobs.js
saltgui/static/scripts/pages/Logout.js
saltgui/static/scripts/pages/Nodegroups.js
saltgui/static/scripts/panels/HighState.js
saltgui/static/scripts/panels/Issues.js
saltgui/static/scripts/panels/Job.js
saltgui/static/scripts/panels/JobsDetails.js
saltgui/static/scripts/panels/Nodegroups.js
saltgui/static/scripts/panels/Options.js
saltgui/static/scripts/panels/Stats.js

When leaving a page, the associated timer-sequence continues.
In some cases, returning to the page starts a new timer, causing multiple timers to be active.
**To Reproduce**
tbd
**Expected behaviour**
Page/panel-related timers must be stopped when leaving the page.
See e.g. `options.js`. function `onHide`.
one positive factor: most timer-sequences are not infinite sequences.
proposal to create panelTimerHelper function.
timer is registered in Panel.
timer is disabled when `isFinished`=true, or when `onHide` is called
parameters:
* actionCallback function
* runFirstTime flag, runs the callback extra immediately
* isFinished function, signals that no more runs are needed
* isSkipped function, signals that this run is not needed
* playPause setting …

timers are not always stopped when leaving a page

---

docs/README.md

This PR changes the file path for PERMISSIONS.md from `docs/PERMISSIONS.md` to `PERMISSIONS.md` in the README.md, which was moved to the `docs` folder and caused the path to PERMISSIONS.md no longer pointing at the correct destination.

Changed File Path to PERMISSIONS.md in README.md

---

docs/README.md
saltgui/static/scripts/Api.js
saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/Documentation.js
saltgui/static/scripts/TargetType.js
saltgui/static/scripts/panels/Login.js

alternative solution for #660
The PR comes with an updated section of the documentation.
Please read that as part of the review.

allow alternative target for test.providers

---

saltgui/static/scripts/Documentation.js

Potential fix for [https://github.com/erwindon/SaltGUI/security/code-scanning/13](https://github.com/erwindon/SaltGUI/security/code-scanning/13)
To fix the issue, we need to ensure that any user-controlled input interpolated into the `html` string is properly escaped to prevent it from being interpreted as HTML. This can be achieved by using a utility function to escape special HTML characters (`<`, `>`, `&`, `"`, `'`) in the `beaconName` variable before including it in the `html` string.
The fix involves:
1. Adding an HTML-escaping utility function to safely encode user-controlled input.
2. Applying this escaping function to `beaconName` before interpolating it into the `html` string.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 13: DOM text reinterpreted as HTML

---

saltgui/static/scripts/CommandBox.js
saltgui/static/scripts/panels/Login.js
saltgui/static/scripts/panels/Panel.js

Hi Team,
I have a Salt Master running on Ubuntu 22.04 with Salt version 3006.1, managing over 1000 minions. To simplify management, I’ve configured SaltGUI for access. However, I’m noticing significant performance issues — particularly, it takes a long time to load and display the list of minions after logging into SaltGUI.
The Salt Master is running on a server with a 16-core CPU and 12 GB of RAM. I’d like to know if this hardware specification is sufficient for managing this number of minions, or if an upgrade is recommended. Additionally, are there any specific configuration best practices for optimizing Salt/SaltGUI performance in large environments like this?
Looking forward to your suggestions.
Best regards,
Sunder

SaltGUI slowness

---

docker/build-and-upload.sh
docker/conf/master-tls
docker/docker-compose-tls.yml
docker/dockerfiles/dockerfile-saltmaster-tls
docs/README.md

This PR adds comprehensive SSL/TLS support to SaltGUI with automated setup scripts, Docker Compose configuration, and Salt state management for secure deployments.
✨ Features Added
🔐 SSL/TLS Infrastructure
Self-signed certificate generation for development/testing
Docker Compose SSL environment with HTTPS endpoints
Salt state for SSL configuration ([saltgui-ssl.sls](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
Automated testing script for end-to-end SSL verification
📁 New Files
[generate-ssl-certs.sh](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) - SSL certificate generation script …

Add SSL/TLS Support for Secure SaltGUI Deployment
